server:
  port: 8003

mybatis:
  # mybatis配置文件所在路径
  config-location: classpath:mybatis/mybatis.cfg.xml
  # 所有Entity别名类所在包
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservicecloud-config-provider-dept
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    dbcp2:
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 初始化连接数
      initial-size: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200

eureka:
  client:
    service-url:
      #单机设置
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: microservicecloud-config-provider-dept-8003
    prefer-ip-address: true

info:
  app:
    name: atguigu-microservicecloud
    author:
      name: feiying
      email: zhaof37@ke.com
  company: 
    name: www.atguigu.com
  build:
    groupId: ${project.groupId}
    artifactId: ${project.artifactId}
    version: ${project.version}
    
